### ISSUE TITLE
Ṍ,Ṏ,Ȭ, and ṹ are broken

### ISSUE THREAD

**Issue by Bronnel721** [vv-monsalve/Freeman#2]
![Screenshot (78)](https://user-images.githubusercontent.com/92538982/205296917-a714012a-630a-4341-a11c-d6555b118378.png)

**Comment by Bronnel721** [comment]
All of those except ṹ are fixed.

**Comment by vv-monsalve** [comment]
Thanks @Bronnel721 for your comment. An update for the font is currently under development and these issues are part of it. Once it is ready it would be released from the main repository for the project: https://github.com/rfuenzalida/Freeman

You can follow the progress and add further comments there.

**Comment by Bronnel721** [comment]
1. Nice font!
2. Thank you for fixing the bugs! Sorry for responding so late, I didn't know you even wrote any.

**Comment by vv-monsalve** [comment]
Happy to hear is working for you now :)
